'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Navbar from '../../components/Navbar';
import { apiFetch } from '../../lib/api';
import { Sparkles, Armchair, ShieldCheck, Ticket, QrCode, ArrowRight, Printer, AlertCircle, ShoppingBag, CreditCard, Film, Calendar, MapPin, Download, Clock } from 'lucide-react';
import Link from 'next/link';
import { Button } from '../../components/ui/Button';

function CheckoutContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const showId = searchParams.get('showId') || '';
  const seatsParam = searchParams.get('seats') || '';

  const [booking, setBooking] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [paymentMethod, setPaymentMethod] = useState<'card' | 'upi' | 'wallet'>('card');
  const [isProcessingPayment, setIsProcessingPayment] = useState(false);
  const [paymentSuccessData, setPaymentSuccessData] = useState<any>(null);

  // Initialize booking
  useEffect(() => {
    if (!showId || !seatsParam) {
      setError('Missing showId or seats parameters. Please select seats first.');
      setLoading(false);
      return;
    }

    const initBooking = async () => {
      try {
        const seatIds = seatsParam.split(',');
        const idempotencyKey = `booking-${showId}-${seatsParam.replace(/,/g, '-')}`;

        // Create booking record (initially PENDING)
        const res = await apiFetch('/bookings', {
          method: 'POST',
          body: JSON.stringify({
            showId,
            seatIds,
            idempotencyKey,
          }),
        });

        setBooking(res.data);
      } catch (err: any) {
        console.error(err);
        setError(err.message || 'Failed to initialize checkout. Your seat locks may have expired.');
      } finally {
        setLoading(false);
      }
    };

    initBooking();
  }, [showId, seatsParam]);

  // Load Razorpay script dynamically
  const loadRazorpayScript = (): Promise<boolean> => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const handleRazorpayPayment = async () => {
    if (!booking) return;
    setIsProcessingPayment(true);

    try {
      const isScriptLoaded = await loadRazorpayScript();
      if (!isScriptLoaded) {
        throw new Error('Failed to load payment gateway script. Please try mock payment instead.');
      }

      const options = {
        key: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID || '', // Must be provided in .env
        amount: Math.round(Number(booking.totalAmount) * 100), // explicitly ensure integer paise
        currency: 'INR',
        order_id: booking.paymentId, // The Razorpay Order ID generated by our backend
        name: 'CineVerse',
        description: `Booking for ${booking.show.movie.title}`,
        notes: {
          bookingId: booking.id,
        },
        handler: async function (response: any) {
          try {
            // Send signature and capture details back to backend to confirm booking
            const confirmRes = await apiFetch('/bookings/confirm-payment', {
              method: 'POST',
              body: JSON.stringify({
                bookingId: booking.id,
                paymentId: response.razorpay_payment_id,
                signature: response.razorpay_signature,
                orderId: response.razorpay_order_id || 'order_mock_' + Date.now(),
              }),
            });
            setPaymentSuccessData(confirmRes.data);
          } catch (err: any) {
            alert(err.message || 'Signature verification failed');
          }
        },
        prefill: {
          name: 'CineVerse Customer',
          email: 'customer@cineverse.com',
        },
        theme: {
          color: '#6366f1',
        },
      };

      const rzp = new (window as any).Razorpay(options);
      rzp.open();
    } catch (err: any) {
      alert(err.message || 'Razorpay initialization failed. Try Mock Payment.');
    } finally {
      setIsProcessingPayment(false);
    }
  };

  // Mock payment bypass for local developer convenience
  const handleMockPayment = async () => {
    if (!booking) return;
    setIsProcessingPayment(true);
    setError(null);

    try {
      const confirmRes = await apiFetch('/bookings/confirm-payment', {
        method: 'POST',
        body: JSON.stringify({
          bookingId: booking.id,
          paymentId: 'pay_mock_' + Math.random().toString(36).substring(2, 9),
          signature: 'MOCK_SIGNATURE',
          orderId: 'order_mock_' + Math.random().toString(36).substring(2, 9),
        }),
      });

      setPaymentSuccessData(confirmRes.data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Mock payment confirmation failed');
    } finally {
      setIsProcessingPayment(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#05050A] text-slate-100 flex flex-col font-sans">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse space-y-4 text-center font-medium text-slate-400">
            <Ticket className="h-10 w-10 text-indigo-500 animate-bounce mx-auto" />
            <p className="text-sm">Creating your temporary lock & booking...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-[#05050A] text-slate-100 flex flex-col font-sans">
        <Navbar />
        <div className="flex-1 flex items-center justify-center p-4">
          <div className="max-w-md w-full bg-[#0A0A12] border border-red-500/20 rounded-3xl p-8 text-center shadow-2xl">
            <div className="w-16 h-16 rounded-full bg-red-500/10 flex items-center justify-center mx-auto mb-4">
              <AlertCircle className="h-8 w-8 text-red-500" />
            </div>
            <h2 className="text-xl font-bold text-white">Checkout Error</h2>
            <p className="text-slate-400 text-sm mt-2 mb-6">{error}</p>
            <Button onClick={() => router.push('/shows')} className="w-full">
              Return to Shows Schedule
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // Render Successful virtual ticket if payment confirmed
  if (paymentSuccessData) {
    const confirmed = paymentSuccessData;
    const dateFormatted = new Date(confirmed.show.startTime).toLocaleDateString('en-US', {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
    const timeFormatted = new Date(confirmed.show.startTime).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
    });

    return (
      <div className="min-h-screen bg-[#05050A] text-slate-100 flex flex-col pb-20 font-sans">
        <Navbar />
        <main className="flex-1 max-w-lg mx-auto w-full px-4 pt-16">
          <div className="text-center mb-10">
            <div className="inline-flex items-center justify-center h-16 w-16 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 mb-4 animate-in zoom-in duration-500 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
              <ShieldCheck className="h-8 w-8" />
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight text-white mb-2">Booking Confirmed!</h1>
            <p className="text-sm text-slate-400">Your ticket is active and ready. Show the QR at the theatre gateway.</p>
          </div>

          {/* Virtual Ticket Ticket Shape Card */}
          <div className="relative bg-[#0A0A12] border border-[#1E1E2E] rounded-[2rem] overflow-hidden shadow-2xl">
            {/* Top segment */}
            <div className="p-8 border-b-2 border-dashed border-[#1E1E2E] relative bg-gradient-to-br from-indigo-500/5 to-transparent">
              <div className="flex justify-between items-start gap-4">
                <div>
                  <span className="text-[10px] text-indigo-400 font-bold uppercase tracking-widest bg-indigo-500/10 px-2.5 py-1 rounded-md border border-indigo-500/20">
                    CineVerse Premium Ticket
                  </span>
                  <h2 className="text-2xl font-bold mt-4 text-white leading-tight">{confirmed.show.movie.title}</h2>
                  <p className="text-sm text-slate-400 mt-1 flex items-center gap-1.5">
                    <MapPin className="w-3.5 h-3.5" /> {confirmed.show.screen.theatre.name}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-6 mt-8">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5" /> Date
                  </span>
                  <p className="text-sm font-semibold text-slate-200">{dateFormatted}</p>
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" /> Time
                  </span>
                  <p className="text-sm font-semibold text-slate-200">{timeFormatted}</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-6 mt-6">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider flex items-center gap-1">
                    <Armchair className="w-3.5 h-3.5" /> Seats
                  </span>
                  <p className="text-sm font-bold text-indigo-400">
                    {confirmed.showSeats.map((ss: any) => `${ss.seat.row}-${ss.seat.number}`).join(', ')}
                  </p>
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider flex items-center gap-1">
                    <Film className="w-3.5 h-3.5" /> Screen
                  </span>
                  <p className="text-sm font-semibold text-slate-200">{confirmed.show.screen.name}</p>
                </div>
              </div>
            </div>

            {/* Inner jagged ticket circles */}
            <div className="absolute left-0 top-[60%] h-8 w-4 bg-[#05050A] rounded-r-full -translate-y-1/2 border-r border-[#1E1E2E]"></div>
            <div className="absolute right-0 top-[60%] h-8 w-4 bg-[#05050A] rounded-l-full -translate-y-1/2 border-l border-[#1E1E2E]"></div>

            {/* Bottom QR Code segment */}
            <div className="p-8 bg-[#05050A]/50 flex flex-col items-center justify-center relative">
              {confirmed.qrCode ? (
                <div className="bg-white p-3 rounded-2xl shadow-lg mb-6 ring-1 ring-[#1E1E2E]">
                  <img
                    src={confirmed.qrCode}
                    alt="Ticket QR Code"
                    className="h-32 w-32 object-contain"
                  />
                </div>
              ) : (
                <div className="h-36 w-36 bg-[#1E1E2E] rounded-2xl flex items-center justify-center mb-6 ring-1 ring-white/5">
                  <QrCode className="h-12 w-12 text-slate-500" />
                </div>
              )}
              <span className="text-[11px] text-slate-400 font-bold tracking-[0.2em] mb-1">SCAN AT ENTRANCE</span>
              <p className="text-[10px] text-slate-500 font-mono">ID: {confirmed.paymentId}</p>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 mt-8">
            <Button
              variant="outline"
              onClick={() => window.print()}
              className="flex-1 flex items-center justify-center gap-2 h-12"
            >
              <Download className="h-4 w-4" /> Save Ticket
            </Button>
            <Link href="/" className="flex-1">
              <Button className="w-full flex items-center justify-center gap-2 h-12">
                Return Home <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </main>
      </div>
    );
  }

  // Render normal Payment Checkout Summary screen
  const dateFormatted = new Date(booking.show.startTime).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  });
  const timeFormatted = new Date(booking.show.startTime).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div className="min-h-screen bg-[#05050A] text-slate-100 flex flex-col pb-20 font-sans">
      <Navbar />
      <main className="flex-1 max-w-6xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-extrabold tracking-tight mb-8 text-white">Review & Checkout</h1>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Booking Summary Columns */}
          <div className="lg:col-span-7 space-y-6">
            <div className="bg-[#0A0A12] border border-[#1E1E2E] rounded-3xl p-8 relative overflow-hidden shadow-xl">
              <div className="absolute top-0 right-0 h-48 w-48 bg-indigo-500/10 rounded-full blur-[40px]"></div>
              
              <span className="text-[10px] text-indigo-400 font-bold uppercase tracking-widest bg-indigo-500/10 px-2 py-1 rounded-md">Booking Summary</span>
              <h2 className="text-3xl font-bold text-white mt-4">{booking.show.movie.title}</h2>
              
              <div className="mt-8 grid grid-cols-2 sm:grid-cols-4 gap-6 pt-6 border-t border-[#1E1E2E] relative z-10">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Theatre</span>
                  <p className="text-sm font-semibold text-slate-200 mt-0.5 truncate">{booking.show.screen.theatre.name}</p>
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Screen</span>
                  <p className="text-sm font-semibold text-slate-200 mt-0.5">{booking.show.screen.name}</p>
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Date</span>
                  <p className="text-sm font-semibold text-slate-200 mt-0.5">{dateFormatted}</p>
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Time</span>
                  <p className="text-sm font-semibold text-slate-200 mt-0.5">{timeFormatted}</p>
                </div>
              </div>
            </div>

            <div className="bg-[#0A0A12] border border-[#1E1E2E] rounded-3xl p-8 shadow-xl">
              <h3 className="text-base font-bold text-white mb-6 flex items-center gap-2">
                <CreditCard className="h-5 w-5 text-indigo-400" /> Select Payment Method
              </h3>
              
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <button
                  type="button"
                  onClick={() => setPaymentMethod('card')}
                  className={`p-5 border rounded-2xl flex flex-col items-center gap-3 transition-all duration-200 ${
                    paymentMethod === 'card'
                      ? 'border-indigo-500 bg-indigo-500/10 text-indigo-400 shadow-[0_0_15px_rgba(99,102,241,0.15)]'
                      : 'border-[#1E1E2E] hover:border-slate-600 bg-[#05050A] text-slate-400'
                  }`}
                >
                  <CreditCard className="h-6 w-6" />
                  <span className="text-xs font-bold uppercase tracking-wider">Card</span>
                </button>
                <button
                  type="button"
                  onClick={() => setPaymentMethod('upi')}
                  className={`p-5 border rounded-2xl flex flex-col items-center gap-3 transition-all duration-200 ${
                    paymentMethod === 'upi'
                      ? 'border-indigo-500 bg-indigo-500/10 text-indigo-400 shadow-[0_0_15px_rgba(99,102,241,0.15)]'
                      : 'border-[#1E1E2E] hover:border-slate-600 bg-[#05050A] text-slate-400'
                  }`}
                >
                  <Sparkles className="h-6 w-6" />
                  <span className="text-xs font-bold uppercase tracking-wider">UPI</span>
                </button>
                <button
                  type="button"
                  onClick={() => setPaymentMethod('wallet')}
                  className={`p-5 border rounded-2xl flex flex-col items-center gap-3 transition-all duration-200 ${
                    paymentMethod === 'wallet'
                      ? 'border-indigo-500 bg-indigo-500/10 text-indigo-400 shadow-[0_0_15px_rgba(99,102,241,0.15)]'
                      : 'border-[#1E1E2E] hover:border-slate-600 bg-[#05050A] text-slate-400'
                  }`}
                >
                  <ShoppingBag className="h-6 w-6" />
                  <span className="text-xs font-bold uppercase tracking-wider">Net Banking</span>
                </button>
              </div>
            </div>
          </div>

          {/* Pricing breakdown sidebar */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-[#0A0A12] border border-[#1E1E2E] rounded-3xl p-8 shadow-xl sticky top-24">
              <h3 className="text-lg font-bold text-white mb-6">Order Summary</h3>
              
              <div className="space-y-4 pb-6 border-b border-[#1E1E2E]">
                <div className="flex justify-between items-center text-sm">
                  <span className="text-slate-400">Tickets ({booking.showSeats.length} Seats)</span>
                  <span className="font-bold text-slate-200">₹{booking.totalAmount.toFixed(2)}</span>
                </div>
                <div className="flex justify-between items-center text-sm">
                  <span className="text-slate-400">Convenience Fee (₹25/ticket)</span>
                  <span className="font-bold text-slate-200">₹{(booking.showSeats.length * 25).toFixed(2)}</span>
                </div>
                <div className="flex justify-between items-center text-sm">
                  <span className="text-slate-400">GST (18%)</span>
                  <span className="font-bold text-slate-200">₹{(booking.totalAmount * 0.18).toFixed(2)}</span>
                </div>
              </div>

              <div className="flex justify-between items-end pt-6 mb-8">
                <span className="text-sm font-bold text-slate-300 uppercase tracking-wider">Total Payable</span>
                <span className="text-3xl font-black text-indigo-400 leading-none">
                  ₹{(booking.totalAmount + booking.showSeats.length * 25 + booking.totalAmount * 0.18).toFixed(2)}
                </span>
              </div>

              <div className="space-y-4">
                <Button
                  size="lg"
                  onClick={handleRazorpayPayment}
                  disabled={isProcessingPayment}
                  className="w-full text-base"
                >
                  {isProcessingPayment ? 'Processing...' : 'Pay Securely'}
                </Button>

                <Button
                  variant="outline"
                  onClick={handleMockPayment}
                  disabled={isProcessingPayment}
                  className="w-full text-xs font-bold border-indigo-500/30 text-indigo-400 hover:bg-indigo-500/10"
                >
                  ⚡ Mock Payment (Dev Bypass)
                </Button>
              </div>

              <p className="text-[11px] text-center text-slate-500 mt-6 font-medium flex items-center justify-center gap-1.5">
                <ShieldCheck className="h-4 w-4 text-emerald-500" /> Secure 256-bit SSL encrypted checkout
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default function CheckoutPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-[#05050A] text-slate-100 flex flex-col font-sans">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse space-y-4 text-center font-medium text-slate-400">
            <Ticket className="h-10 w-10 text-indigo-500 animate-bounce mx-auto" />
            <p className="text-sm">Preparing secure checkout...</p>
          </div>
        </div>
      </div>
    }>
      <CheckoutContent />
    </Suspense>
  );
}
